import { LLMProvider, ChatMessage } from './llm-provider';

export class GeminiAdapter implements LLMProvider {
  private apiKey: string;
  
  constructor(apiKey: string) {
    this.apiKey = apiKey;
  }

  async generateDocstring(codeSnippet: string, contextFacts: string[]): Promise<string> {
    console.log(`[GeminiAdapter] Generating docstring for snippet of length ${codeSnippet.length}`);
    return "This is a docstring generated by Google Gemini.";
  }

  async chat(messages: ChatMessage[], contextFacts: string[]): Promise<string> {
    console.log(`[GeminiAdapter] Chatting with Gemini API`);
    return "This is a response generated by Google Gemini using the provided context.";
  }
  
  async generateEmbedding(text: string): Promise<number[]> {
    console.log(`[GeminiAdapter] Generating semantic embedding for text: ${text}`);
    // Returning a dummy 1536-dimensional vector for MVP
    return new Array(1536).fill(0.1);
  }
}
